Repository cypress-io/eslint-plugin-cypress, pull requests merged in 2024-05, with the labels that each got.

#200 fix(deps): update semantic-release to 23.0.8
  package-lock.json
  package.json
Labels: bug

#189 feat: apply no-pause rule recursively
  docs/rules/no-pause.md
  lib/rules/no-pause.js
  tests/lib/rules/no-pause.js
Labels: type: enhancement

#141 fix: issue with unsafe to chain command that is not an action
  lib/rules/unsafe-to-chain-command.js
  tests/lib/rules/unsafe-to-chain-command.js
Labels: bug

#201 docs: add document for FlatCompat use
  FLAT-CONFIG.md
  README.md
Labels: type: enhancement

#202 chore: migrate internal linting to flat config
  .eslintrc.js
  eslint.config.mjs
  package-lock.json
  package.json
Labels: type: enhancement

#205 tests: save legacy tests
  circle.yml
  jest.config-legacy.js
  package.json
  tests-legacy/config.js
  tests-legacy/lib/rules/assertion-before-screenshot.js
  tests-legacy/lib/rules/no-assigning-return-values.js
  tests-legacy/lib/rules/no-async-before.js
  tests-legacy/lib/rules/no-async-tests.js
  tests-legacy/lib/rules/no-force.js
  tests-legacy/lib/rules/no-pause.js
  tests-legacy/lib/rules/no-unnecessary-waiting.js
  tests-legacy/lib/rules/require-data-selectors.js
  tests-legacy/lib/rules/unsafe-to-chain-command.js
Labels: type: enhancement

#209 docs: rework contributor instructions
  CONTRIBUTING.md
Labels: type: enhancement

#207 chore: migrate to RuleTester v9
  circle.yml
  tests/lib/rules/assertion-before-screenshot.js
  tests/lib/rules/no-assigning-return-values.js
  tests/lib/rules/no-async-before.js
  tests/lib/rules/no-async-tests.js
  tests/lib/rules/no-force.js
  tests/lib/rules/no-pause.js
  tests/lib/rules/no-unnecessary-waiting.js
  tests/lib/rules/require-data-selectors.js
  tests/lib/rules/unsafe-to-chain-command.js
Labels: type: enhancement

#210 chore(deps): update eslint to 9.2.0
  package-lock.json
  package.json
Labels: type: enhancement

#211 test: add property ordering rules
  eslint.config.mjs
  tests-legacy/lib/rules/unsafe-to-chain-command.js
  tests/lib/rules/unsafe-to-chain-command.js
Labels: type: enhancement

#213 chore(deps): update eslint to 9.3.0 with plugin updates
  package-lock.json
  package.json
Labels: type: enhancement

#212 feat: add flat configurations
  CONTRIBUTING.md
  FLAT-CONFIG.md
  README.md
  legacy.js
  lib/flat.js
  package.json
  tests-legacy/config.js
  tests/config.js
Labels: type: feature
