Repository cypress-io/eslint-plugin-cypress, pull requests merged in 2025-04, with the labels that each got.

#252 ci: add test project
  circle.yml
  eslint.config.mjs
  test-project/.gitignore
  test-project/README.md
  test-project/cypress.config.js
  test-project/cypress/e2e/1-getting-started/todo.cy.js
  test-project/cypress/e2e/2-advanced-examples/actions.cy.js
  test-project/cypress/e2e/2-advanced-examples/aliasing.cy.js
  test-project/cypress/e2e/2-advanced-examples/assertions.cy.js
  test-project/cypress/e2e/2-advanced-examples/connectors.cy.js
  test-project/cypress/e2e/2-advanced-examples/cookies.cy.js
  test-project/cypress/e2e/2-advanced-examples/cypress_api.cy.js
  test-project/cypress/e2e/2-advanced-examples/files.cy.js
  test-project/cypress/e2e/2-advanced-examples/location.cy.js
  test-project/cypress/e2e/2-advanced-examples/misc.cy.js
  test-project/cypress/e2e/2-advanced-examples/navigation.cy.js
  test-project/cypress/e2e/2-advanced-examples/network_requests.cy.js
  test-project/cypress/e2e/2-advanced-examples/querying.cy.js
  test-project/cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  test-project/cypress/e2e/2-advanced-examples/storage.cy.js
  test-project/cypress/e2e/2-advanced-examples/traversal.cy.js
  test-project/cypress/e2e/2-advanced-examples/utilities.cy.js
  test-project/cypress/e2e/2-advanced-examples/viewport.cy.js
  test-project/cypress/e2e/2-advanced-examples/waiting.cy.js
  test-project/cypress/e2e/2-advanced-examples/window.cy.js
  test-project/cypress/fixtures/example.json
  test-project/cypress/support/commands.js
  test-project/cypress/support/e2e.js
  test-project/eslint-configs/eslint.default.mjs
  test-project/eslint-configs/eslint.globals.mjs
  test-project/eslint-configs/eslint.recommended.mjs
  test-project/eslint.config.mjs
  test-project/package.json
Labels: type: enhancement

#253 fix(deps): update all dependencies
  package-lock.json
  package.json
Labels: bug

#254 docs: add PR merge guidelines for maintainers
  CONTRIBUTING.md
Labels: type: enhancement

#249 feat: add no-chained-get rule
  README.md
  docs/rules/no-chained-get.md
  legacy.js
  lib/flat.js
  lib/rules/no-chained-get.js
  tests/lib/rules/no-chained-get.js
Labels: type: feature
